apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: tree-deployment
spec:
  selector:
    matchLabels:
      app: tree-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tree-app
    spec:
      containers:
      - name: tree-app
        image: 192.168.65.0/24/tree-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000


